parameters:
  - name: projectDirectory
    type: string
    default: ""
  - name: artifactName
    type: string
    default: "salad-app"

jobs:
  - job: BuildPublish
    displayName: Build/Publish
    variables:
      - name: NUGET_PACKAGES
        value: $(Pipeline.Workspace)/.nuget/packages
      - group: DevOps Access Tokens
    steps:
      - template: ../tasks/install-dotnet-step.yaml
        parameters:
          projectDirectory: ${{ parameters.projectDirectory }}
      - template: ../tasks/cache-paket-step.yaml
        parameters:
          projectDirectory: ${{ parameters.projectDirectory }}
          cacheDirectory: $(NUGET_PACKAGES)
          cacheKey: cloud-backend
      - template: ../tasks/pwsh-step.yaml
        parameters:
          projectDirectory: ${{ parameters.projectDirectory }}
          scriptFile: initialize.ps1
      - template: ../tasks/pwsh-step.yaml
        parameters:
          projectDirectory: ${{ parameters.projectDirectory }}
          scriptFile: salad-app/build.ps1
          env:
            azure_credential: $(AZURE_DEVOPS_PAT)
      - template: ../tasks/download-secure-file-step.yaml
        parameters:
          referenceName: gcrKeyJson
          fileId: 38b216da-f6d9-4646-9325-6c2770858af9
          conditional: true
      - template: ../tasks/pwsh-step.yaml
        parameters:
          projectDirectory: ${{ parameters.projectDirectory }}
          scriptFile: salad-app/publish.ps1
          conditional: true
          env:
            KEY_FILE_PATH: $(gcrKeyJson.secureFilePath)
      - template: ../tasks/publish-artifact-step.yaml
        parameters:
          artifactPath: ${{ parameters.projectDirectory }}/saladcloud-admin.tar.gz
          artifactName: ${{ parameters.artifactName }}
          conditional: true
