defaultSemverRangePrefix: ""

logFilters:
  - code: YN0032
    level: discard
  - code: YN0060
    level: discard
  - code: YN0061
    level: discard
  - code: YN0062
    level: discard

npmScopes:
  saladtechnologies:
    npmRegistryServer: "https://pkgs.dev.azure.com/SaladTechnologies/_packaging/SaladTechnologies/npm/registry/"

packageExtensions:
  "@storybook/addon-docs@6.5.16":
    peerDependencies:
      "@babel/core": ^7.13.0
      webpack: ">=2"
  "@storybook/docs-tools@6.5.16":
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  "@storybook/mdx1-csf@0.0.1":
    peerDependencies:
      "@babel/core": ^7.13.0
  "@storybook/preset-create-react-app@4.1.2":
    dependencies:
      react-refresh: ^0.11.0
    peerDependencies:
      typescript: ">= 4.3.x"
      webpack: ">=4.43.0 <6.0.0"
  "@storybook/telemetry@6.5.16":
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.4.1.cjs
