parameters:
  - name: projectDirectory
    type: string
    default: ''
  - name: cacheDirectory
    type: string
    default: ''
  - name: cacheKey
    type: string
    default: ''

steps:
  - task: Cache@2
    displayName: Cache Paket packages
    inputs:
      key: '"${{ parameters.cacheKey }}" | "version1" | "paket" | "$(Agent.OS)" | ${{ parameters.projectDirectory }}/paket.lock'
      restoreKeys: |
        "${{ parameters.cacheKey }}" | "version1" | "paket" | "$(Agent.OS)"
        "${{ parameters.cacheKey }}" | "version1" | "paket"
      path: ${{ parameters.cacheDirectory }}
