parameters:
  - name: referenceName
    type: string
    default: ""
  - name: fileId
    type: string
    default: ""
  - name: conditional
    type: boolean
    default: false

steps:
  - task: DownloadSecureFile@1
    name: ${{ parameters.referenceName }}
    displayName: "Download secure file"
    condition: or(not(${{ parameters.conditional }}), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
    inputs:
      secureFile: ${{ parameters.fileId }}
