parameters:
  - name: projectDirectory
    type: string
    default: ''
  - name: authenticateNuGet
    type: boolean
    default: true
  - name: authenticatePaket
    type: boolean
    default: true

steps:
  - task: UseDotNet@2
    displayName: Install .NET
    inputs:
      packageType: sdk
      useGlobalJson: true
      workingDirectory: ${{ parameters.projectDirectory }}
  - ${{ if eq(parameters.authenticateNuGet, true) }}:
      - task: NuGetAuthenticate@0
        displayName: Login to Azure Artifacts (NuGet)
  - ${{ if eq(parameters.authenticatePaket, true) }}:
      - pwsh: |
          & dotnet tool install --global --configfile ./.azure-pipelines/tasks/global-tool-nuget.config --ignore-failed-sources paket
          & paket config add-credentials https://pkgs.dev.azure.com/SaladTechnologies/_packaging/SaladTechnologies/nuget/v3/index.json --username ApiKey --password $Env:SYSTEM_ACCESSTOKEN --verify
        displayName: Login to Azure Artifacts (Paket)
        workingDirectory: ${{ parameters.projectDirectory }}
        env:
          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
