parameters:
  - name: artifactPath
    type: string
    default: ""
  - name: artifactName
    type: string
    default: ""
  - name: conditional
    type: boolean
    default: false

steps:
  - task: PublishPipelineArtifact@1
    displayName: Publish Artifacts
    condition: or(not(${{ parameters.conditional }}), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
    inputs:
      targetPath: ${{ parameters.artifactPath }}
      artifactName: ${{ parameters.artifactName }}
      artifactType: pipeline
