parameters:
  - name: projectDirectory
    type: string
    default: ""
  - name: scriptFile
    type: string
    default: ""
  - name: env
    type: object
    default: {}
  - name: conditional
    type: boolean
    default: false

steps:
  - task: PowerShell@2
    displayName: pwsh ${{ parameters.scriptFile }}
    condition: or(not(${{ parameters.conditional }}), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), ne(variables['Build.Reason'], 'PullRequest')))
    inputs:
      filePath: ${{ parameters.projectDirectory }}/.azure-pipelines/${{ parameters.scriptFile }}
      pwsh: true
      workingDirectory: ${{ parameters.projectDirectory }}
    env:
      ${{ insert }}: ${{ parameters.env }}
